### ISSUE TITLE
ES5+ Site Plugins disabled / directory missing in the plugin zip

### ISSUE THREAD

**Issue by szorg** [ForgeRock/es-change-feed-plugin#8] opened 2017-07-31 17:05 UTC
It looks like this might just not be compatible in its current form with ES5+.. I'm not sure if this was accounted for with your new releases, but they no longer support site plugins which causes errors like this, with built versions and with downloaded binaries:

Alternatively of course I don't know what the heck I'm doing.. any suggestions here, if that might be the case? 

$ sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install file:///tmp/es-changes-
feed-plugin.zip
-> Downloading file:///tmp/es-changes-feed-plugin.zip
[=================================================] 100%  
ERROR: `elasticsearch` directory is missing in the plugin zip

**Comment by jurgc11** [comment] 2017-08-02 09:54
Duplicate of #7

**Closed by jurgc11** 2017-08-02 09:54 UTC
